TouchOfLibrary/urls.py
from django.contrib import admin
from django.urls import path
import TouchOfLibrary.views as views

urlpatterns = [
    path('admin/', admin.site.urls)
]

from django.conf.urls import include
from django.conf.urls import url

urlpatterns += [
    url(r'^library/', include('library.urls')),
    path('library/', include('library.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

from django.views.generic import RedirectView

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/library/', permanent=True)),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/urls.py
from django.conf.urls import url

from library.views.document.location import LocationListView, create_location, location_delete_confirmation, \
    location_update, location_delete
from library.views.tag.tag_create import tag_create
from library.views.tag.tag_update import tag_update
from library.views.tag.tag_delete import tag_delete
from library.views.tag.tag_delete import tag_deleteconfirm

from library.views import *

# Maintenance routines
from library.models import Reservation
from library.views.author import author_create, author_delete
from library.views.author.author_delete import author_deleteconfirm
from library.views.author.author_update import author_update
from library.views.type.type_create import type_create
from library.views.type.type_update import type_update
from library.views.type.type_delete import type_delete
from library.views.type.type_delete import type_deleteconfirm
from library.views.document.priority_queue import get_priority_queue, request_all_view

try:
    Reservation.clean_old_reservations()
except:
    pass

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^dashboard/$', dashboard, name='dashboard'),

    url(r'^location/$', LocationListView.as_view(), name='location_list'),
    url(r'^location/create/$', create_location, name='create_location'),
    url(r'^location/(?P<id>\d+)/delete_confirm/$', location_delete_confirmation, name='delete_location_confirm'),
    url(r'^location/(?P<id>\d+)/update/$', location_update, name='update_location'),
    url(r'^location/(?P<id>\d+)/delete/$', location_delete, name='delete_location'),

    url(r'^document/$', DocumentListView.as_view(), name='document'),
    url(r'^document/(?P<id>\d+)$', get_document_detail, name='document-detail'),
    url(r'^document/request_all_copies/(?P<pk>\d+)$', request_all_view, name='request_all'),

    url(r'^authors/$', AuthorsListView.as_view(), name='authors'),
    url(r'^authors/(?P<pk>\d+)$', AuthorDetailView.as_view(), name='author-detail'),

    url(r'^reserved/$', reservation_list, name='reservation-list'),
    url(r'^reserve_document/(?P<copy_id>[0-9a-z-]+)$', reserve_document, name='reserve-document'),
    url(r'^notification_response/(?P<id>[0-9a-z-]+)$',
        notification_response, name='notification-response'),

    url(r'^request_document/(?P<document_id>\d+)$', request_document, name='request-document'),
    url(r'^edit_document_request/(?P<id>\d+)/(?P<action>[\w-]+)/$', edit_document_request,
        name='edit-document-request'),

    url(r'^issued/$', giveout_list, name='giveout-list'),
    url(r'^issued/(?P<id>\d+)$', giveout_confirmation, name='giveout-confirmation'),

    url(r'^return_document/(?P<id>\d+)$', return_document, name='return-document'),
    url(r'^renew_document/(?P<id>\d+)$', renew_document, name='renew-document'),

    url(r'^users/(?P<pk>\d+)/permissions$', edit_user_perms, name='edit-user-perms'),

    url(r'^patrons/$', patrons_list, name='patrons-list'),
    url(r'^patrons/(?P<id>\d+)$', patron_details, name='patron-details'),
    url(r'^patrons/(?P<pk>\d+)/edit$', edit_patron, name='patron_edit'),
    url(r'^patrons/add$', add_patron, name='patron-add'),
    url(r'^patrons/(?P<pk>\d+)/delete$', delete_patron, name='patron-delete'),

    url(r'^document/create', DocumentCreate.as_view(), name='document-create'),
    url(r'^document/instance/create/(?P<pk>[0-9a-f-]+)$', instance_create, name='documentinstance-create'),
    url(r'^document/instance/update/(?P<id>[0-9a-f-]+)$', instance_update, name='documentinstance-update'),
    url(r'^document/instance/delete/(?P<id>[0-9a-f-]+)$', instance_delete, name='documentinstance-delete'),
    url(r'^document/instance/delete/confirm/(?P<id>[0-9a-f-]+)$', instance_deleteconfirm,
        name='documentinstance-deleteconfirm'),
    url(r'^document/update/(?P<pk>\d+)$', DocumentUpdate.as_view(), name='document-update'),
    url(r'^document/delete/(?P<pk>\d+)$', DocumentDelete.as_view(), name='document-delete'),
    url(r'^document/upload_photo', upload, name='document-upload-photo'),
    url(r'^document/upload_photo_complete', direct_upload_complete, name='document-upload-photo-complete'),
    url(r'^authors/create', author_create, name='author-create'),
    url(r'^authors/update/(?P<id>\d+)$', author_update, name='author-update'),
    url(r'^authors/delete/confirm/(?P<id>\d+)$', author_deleteconfirm, name='author-deleteconfirm'),
    url(r'^authors/delete/(?P<id>\d+)$', author_delete, name='author-delete'),

    url(r'^types/$', TypeListView.as_view(), name='types'),
    url(r'^types/(?P<pk>\d+)$', TypeDetailView.as_view(), name='types-detail'),
    url(r'^types/create', type_create, name='type-create'),
    url(r'^types/update/(?P<id>\d+)$', type_update, name='type-update'),
    url(r'^types/delete/confirm/(?P<id>\d+)$', type_deleteconfirm, name='type-deleteconfirm'),
    url(r'^types/delete/(?P<id>\d+)$', type_delete, name='type-delete'),

    url(r'^tags/$', TagListView.as_view(), name='tags'),
    url(r'^tags/create', tag_create, name='tag-create'),
    url(r'^tags/update/(?P<id>\d+)$', tag_update, name='tag-update'),
    url(r'^tags/delete/confirm/(?P<id>\d+)$', tag_deleteconfirm, name='tag-deleteconfirm'),
    url(r'^tags/delete/(?P<id>\d+)$', tag_delete, name='tag-delete'),

    url(r'^populate_database/$', populate_db, name='debug-populate-database'),
    url(r'^document/(?P<id>\d+)/queue$', get_priority_queue, name='priority_queue'),

    url(r'^place_search/$', SearchListView.as_view(), name='search'),
    url(r'^logs/$', log_list, name='logs-list'),
    url(r'^search/$', SearchListView.as_view(), name='search'),
]

library/models.py
import datetime
import uuid

import cloudinary.models
import pytz
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMultiAlternatives
from django.core.mail import send_mail
from django.db import models
from django.db.models import Q
from django.template.loader import render_to_string
from django.urls import reverse


class User(AbstractUser):
    # Patron attributes
    is_patron = models.BooleanField(default=False)
    is_limited = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=200, blank=True)
    telegram = models.CharField(max_length=20, blank=True)
    patron_type = models.ForeignKey('PatronType', on_delete=models.SET_NULL, null=True, blank=True)

    def email_user(self, mail_subject, message, from_email=None, **kwargs):
        send_mail(mail_subject, message, from_email, [self.email], **kwargs)

    def form_mail_about_deletion(self):
        n_line = "%0A%0A"
        return "mailto:%s?subject=The deletion of your account in Library&body=Dear %s %s,%sThis is Touch of Library. " \
               "We inform you that your account has been deleted." \
               "%sReason:" \
               "%sRegards,%sTouch of Library." % (
                   self.email, self.first_name, self.last_name, n_line, n_line, n_line,
                   n_line[:3])

    class Meta:
        permissions = (
            ("add_patron", "Can add patron"),
            ("change_patron", "Can change patron"),
            ("delete_patron", "Can delete patron"),
            ("dashboard_access", "Can access to dashboard")
        )

    def get_absolute_url(self):
        return reverse('patron-details', args=[str(self.id)])

    def __str__(self):
        return '[%d] %s %s (%s), %s, %s, TG: %s' % (
            self.id, self.first_name, self.last_name, self.patron_type, self.phone_number, self.address,
            self.telegram)


class Document(models.Model):
    """
    Model of abstract document
    """
    # document attributes
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author', help_text='Select authors')
    description = models.TextField(max_length=1000, help_text="Enter a description of the document")
    type = models.ForeignKey('DocType', on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField('Tag', help_text="Select tags")
    last_quantity = models.IntegerField(
        help_text='This field is used for storing quantity after recalculation. DO NOT USE IT, use quantity() instead!',
        null=True)
    bestseller = models.BooleanField(default=False)
    quantity_synced = models.BooleanField(default=False)
    is_reference = models.BooleanField(default=False, help_text="Reference materials can not be borrowed.")
    image = cloudinary.models.CloudinaryField('image', blank=True)

    def quantity(self) -> int:
        if not self.quantity_synced:
            n = len(DocumentInstance.objects.filter(document_id=self.id, status='a'))
            self.last_quantity = n
            self.quantity_synced = True
            self.save()
        else:
            n = self.last_quantity
        return n

    def quantity_real(self):
        return len(DocumentInstance.objects.filter(Q(document_id=self.id) & (Q(status='a') | Q(status='r'))))

    def str_authors(self):
        authors_list = [str(x) for x in list(self.authors.all())]
        return ', '.join(authors_list)

    def days_available(self, user):
        if user.patron_type is None:
            return 0
        if user.patron_type.position == 'p':
            return self.type.max_days_privileges
        elif user.patron_type.position == 'v':
            return self.type.max_days_visiting
        else:
            if self.bestseller:
                return self.type.max_days_bestseller
            else:
                return self.type.max_days

    # document features
    def __str__(self):
        return '%s %s "%s"' % (str(self.type).lower(),
                               self.str_authors(), self.title)

    def get_absolute_url(self):
        return reverse('document-detail', args=[str(self.id)])


class DocumentInstance(models.Model):
    """
        Model of real document in the library
    """
    # instance attributes
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique document ID")
    document = models.ForeignKey('Document', on_delete=models.CASCADE, null=True)
    due_back = models.DateField(null=True, blank=True)

    DOCUMENT_STATUS = (
        ('a', 'Available'),
        ('g', 'Given out'),
        ('r', 'Reserved'),
        ('m', 'Maintenance')
    )

    status = models.CharField(max_length=1, choices=DOCUMENT_STATUS, blank=True, default='d')

    location = models.ForeignKey('LibraryLocation', on_delete=models.SET_NULL, null=True, blank=True)
    price = models.FloatField(help_text='Price in RUB', null=True)
    holder = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    additional_field1 = models.CharField(max_length=500, blank=True)
    additional_field2 = models.CharField(max_length=500, blank=True)
    additional_field3 = models.CharField(max_length=500, blank=True)
    additional_field4 = models.CharField(max_length=500, blank=True)
    additional_field5 = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ["due_back"]

    # def __str__(self):
    #     return str(self.document.title)

    def form_return_request_mail(self):
        n_line = "%0A%0A"
        message = "mailto:%s?subject=Touch of Library: Please return document&body=Dear %s %s,%sThis is Touch of Library. " \
                  "Please return %s to the library as soon as possible." \
                  "%sRegards,%sTouch of Library." % (
                      self.holder.email, self.holder.first_name, self.holder.last_name, n_line, self.summary(), n_line,
                      n_line[:3])
        print(message)

        return message

    def overdue_days(self):
        if (self.status == 'g') & (datetime.date.today() > self.due_back):
            return (datetime.date.today() - self.due_back).days
        else:
            return 0

    def fine(self):
        overdue = self.overdue_days()
        if overdue * 100 > self.price:
            return self.price
        else:
            return overdue * 100

    def DEBUG_give_out(self, document, user, timestamp):
        self.holder = user
        self.due_back = timestamp + datetime.timedelta(days=document.days_available(user))
        self.status = 'g'
        self.save()
        document.quantity_synced = False
        GiveOut.objects.create(user=user, document=document, document_instance=self)
        if timestamp is not None:
            GiveOut.objects.filter(user=user, document_instance=self).update(timestamp=timestamp)

    def clean_giveout(self, request):
        self.status = 'a'
        self.holder = None
        self.due_back = None
        self.document.quantity_synced = False
        self.save()
        self.document.save()
        self.reserve_from_queue(request)

    def reserve(self, request, user, notify_user):
        if self.status == "a" and not self.document.is_reference:
            self.status = 'r'
            self.save()
            if notify_user:
                reservation = Reservation.objects.create(user=user, document=self.document, document_copy=self,
                                                         confirmed=False)
                mail_subject = 'Touch of Library: Copy Available'
                current_site = get_current_site(request)
                message = render_to_string('mails/copy_available.html', {
                    'user': user,
                    'document': self.document,
                    'domain': current_site.domain,
                    'summary': self.summary(),
                    'reservation_due': reservation.due_date(),
                    'reservation_id': reservation.id
                })

                to_email = user.email
                email = EmailMultiAlternatives(mail_subject, message, to=[to_email])
                email.attach_alternative(message, "text/html")
                email.send()
                reservation.save()
            else:
                Reservation.objects.create(user=user, document=self.document, document_copy=self,
                                           confirmed=True).save()

    def reserve_from_queue(self, request):
        queue = DocumentRequest.objects.filter(document_id=self.document_id)
        if queue:
            top = queue.first()
            for e in queue:
                if e.importance() > top.importance():
                    top = e
            self.reserve(request, top.user, True)
            top.delete()

    def summary(self):
        fields = [self.additional_field1, self.additional_field2,
                  self.additional_field3, self.additional_field4, self.additional_field5]
        fields_str = ', '.join([x for x in fields if x != ""])
        return '%s %s "%s" (%s)' % (str(self.document.type),
                                    self.document.str_authors(), self.document.title, fields_str)

    @property
    def is_overdue(self):
        if self.due_back is None:
            return False
        if datetime.date.today() > self.due_back:
            return True
        else:
            return False

    # Constraints
    def clean(self):
        if self.price < 0:
            raise ValidationError('Price can not be less than zero')

    # instance attributes
    def __str__(self):
        return '%s' % self.document.title

    def get_absolute_url(self):
        return reverse('document-detail', args=[str(self.document.id)])

library/views/dashboard.py
from django.shortcuts import render
from library.models import Reservation, GiveOut, GiveOutLogEntry, DocumentRequest
from django.contrib.auth.decorators import login_required
from django.contrib import auth
import cloudinary


@login_required
def dashboard(request):
    image = cloudinary.CloudinaryImage("UI/user.png")
    user = auth.get_user(request)
    reservation_list = Reservation.objects.filter(user_id=user.id)
    giveout_list = GiveOut.objects.filter(user_id=user.id)
    giveout_log_list = GiveOutLogEntry.objects.filter(user_id=user.id)
    request_list = DocumentRequest.objects.filter(user_id=user.id)

    return render(
        request,
        'dashboard.html',
        context={'patron_user': user,
                 'reservation_table': reservation_list,
                 'giveout_table': giveout_list,
                 'giveout_log_table': giveout_log_list,
                 'request_table': request_list,
                 'image': image},
    )

library/views/index.py
from django.shortcuts import render, redirect


def index(request):
    """
    home page template
    """
    if request.user.is_authenticated:
        return redirect('document')
    else:
        return render(request, 'index.html')

library/templates/author_deleteconfirm.html
{% extends "base_generic.html" %}

{% block content %}
    {% if perms.library.change_documentinstance %}
        <h1>You are deleting an author {{ instance.first_name }} {{ instance.last_name }}</h1>

        </br>
        <div><a href="{% url 'author-delete' id=id %}">Delete him</a>

    {% endif %}
{% endblock %}

library/templates/author_update.html
{% extends "base_generic.html" %}

{% block content %}
    {% if perms.library.change_documentinstance %}
        <h1>Author: {{ form.instance.first_name }} {{ form.instance.last_name }}</h1>
        <form action="" method="post">
            <table>
                {{ form.as_table }}
            </table>
            <input class="button" type="submit" name="submit" value="Submit">
            {% csrf_token %}
        </form>

    {% endif %}
{% endblock %}

library/templates/dashboard.html
{% extends "base_generic.html" %}
{#{% load cloudinary %}#}
{% load bootstrap %}


{% block content %}
    <body style="background: lightseagreen">
    <h1 align="center" style="color: white;">Dashboard</h1>

    {#    {% cloudinary image width=320 height=240 %}#}
    {#    {% cloudinary_direct_upload_field request=request %}#}
    {% if perms.library.dashboard_access %}
        <h3 align="center" style="color: white;">Librarian activities</h3>
        <div class="container-fluid">
            <div class="row" style="padding-top: 50px">
                <div class="col-sm-4">

                    <div class="card" style="width: 100%; display: inline-block">
                        <div class="card-body">
                            {% if perms.library.change_user %}
                                <h4 class="card-title">User management</h4>
                                <p><a href="{% url 'patrons-list' %}" class="btn btn-success">Users</a>
                                    {% elif perms.library.change_patron %}
                                <h4 class="card-title">Patron management</h4>
                                <p><a href="{% url 'patrons-list' %}" class="btn btn-success">Patrons</a>
                            {% endif %}
                            <a href="{% url 'reservation-list' %}" class="btn btn-success">Reservations</a>
                            <a href="{% url 'giveout-list' %}" class="btn btn-success">Check-outs</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="card" style="width:100%; display: inline-block">
                        <div class="card-body">
                            <h4 class="card-title">Documents</h4>
                            <p><a href="{% url 'document-upload-photo' %}" class="btn btn-success">New document</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="card" style="width:100%; display: inline-block">
                        <div class="card-body">
                            <h4 class="card-title">Authors</h4>
                            <p><a href="{% url 'authors' %}" class="btn btn-success">List of Authors</a>
                                <a href="{% url 'author-create' %}" class="btn btn-success">New author</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="card" style="width: 100%; display: inline-block">
                        <div class="card-body">
                            <h4 class="card-title">Tags</h4>
                            <p><a href="{% url 'tags' %}" class="btn btn-success">Tags management</a>

                        </div>
                    </div>
                </div>
            </div>


            <div class="row" style="padding-top: 50px">
                <div class="col-sm-3">
                    <div class="card" style="width: 100%; display: inline-block">
                        <div class="card-body">
                            <h4 class="card-title">Types</h4>
                            <p><a href="{% url 'types' %}" class="btn btn-success">Document Types management</a>

                        </div>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="card" style="width: 100%; display: inline-block">
                        <div class="card-body">
                            <h4 class="card-title">Locations</h4>
                            <p><a href="{% url 'location_list' %}" class="btn btn-success">Locations management</a></p>
                        </div>
                    </div>
                </div>
            </div>
            {% if user.is_staff or perms.library.view_logs %}
                <div class="row" style="padding-top: 50px; padding-bottom: 50px">
                <div class="col-sm-4">
                    <div class="card" style="width: 100%; display: inline-block">
                        <div class="card-body">
                            <h4 style="color: red;" class="card-title">Staff Area</h4>
                            {% if user.is_staff %}
                                <a href="/admin" class="btn btn-success">Admin Panel</a>
                                <a href="{% url 'debug-populate-database' %}" class="btn btn-success">Populate
                                    database</a>
                            {% endif %}
                            <a href="{% url 'logs-list' %}" class="btn btn-info">Logs</a>
                        </div>
                    </div>
                </div>

            {% endif %}
            </div>
        </div>


    {% else %}
        {% if not user.is_active %}
            <div class="alert alert-danger">
                <strong>Attention!</strong> Your account is not active.
            </div>
        {% elif user.is_limited %}
            <div class="alert alert-warning">
                <strong>Attention! </strong>Your account is limited. Please visit Touch of Library for further
                information.
            </div>
        {% endif %}
        {% include "library/user_infromation_template.html" %}
    {% endif %}
    </body>
{% endblock %}

library/templates/documentinstance_deleteconfirm.html
{% extends "base_generic.html" %}

{% block content %}

    <body style="background: lightseagreen">
    {% if perms.library.change_document %}
        <ul class="list-group" style="width: 80%; margin: 2% 10% 2% 10%;">
            <li class="list-group-item">
                <div class="jumbotron">
                    <h1 align="center">Delete a copy</h1>
                </div>
                {% if perms.library.delete_documentinstance %}
                    {% if instance.status == 'g' %}
                        You are trying to delete a copy of <strong>{{ instance.document.title }}</strong>
                        </br>
                        <div class="text-danger"> Given out copies cannot be deleted</div>
                    {% endif %}
                    <div align="center">
                        You are deleting a copy of <strong>{{ instance.document.title }}</strong>
                        </br>
                        Are you sure you want to remove that copy from the library?
                        </br>
                        <div class="text-danger"> Existing reservations will be canceled</div>
                        </br>
                        <div><a class="btn btn-danger" href="{% url 'documentinstance-delete' id=id %}">Delete copy</a>
                        </div>
                    </div>
                {% endif %}
            </li>

        </ul>

    {% else %} You are not allowed to be here
    {% endif %}


    </body>

{% endblock %}

library/templates/tag_deleteconfirm.html
{% extends "base_generic.html" %}

{% block content %}
    <body style="background: lightseagreen">
    {% if perms.library.delete_tag %}
        <ul class="list-group" style="width: 80%; margin: 2% 10% 2% 10%;">
            <li class="list-group-item">
                <div class="jumbotron">
                    <h1 align="center">You are deleting tag "{{ instance.caption }}"</h1>
                </div>
                {% if not wrong_docs  and not given_out %}
                    <div align="center">
                        <a class="btn btn-danger" role="button" href="{% url 'tag-delete' id=id %}">Delete</a>
                    </div>
                {% else %}
                    <div class="alert alert-danger" align="center">
                        This tag is associated with next documents, delete them before deleting tag.
                    </div>

                    <table class="table">
                        {% for doc in given_out %}
                            <tr>
                                <td><a href="{{ doc.get_absolute_url }}">
                                    {{ doc.title }}
                                </a></td>
                                <td>
                                    {{ doc.type }}
                                </td>
                                {% if perms.library.delete_document %}
                                    <td>
                                        <h6 title="Imposible to delete" class="text-danger">Given out</h6>
                                    </td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                        {% for docs in wrong_docs %}
                            <tr>
                                <td><a href="{{ docs.get_absolute_url }}">
                                    {{ docs.title }}
                                </a></td>
                                <td>
                                    {{ docs.type }}
                                </td>
                                {% if perms.library.delete_document %}
                                    <td>
                                        <a href="{% url 'document-delete' pk=docs.id %}" class="btn btn-danger"
                                           role="button">Delete</a>
                                    </td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </li>
        </ul>

    {% else %} You are not allowed to be here
    {% endif %}


    </body>
{% endblock %}

library/templates/type_deleteconfirm.html
{% extends "base_generic.html" %}

{% block content %}
     <body style="background: lightseagreen">
    {% if perms.library.delete_tag %}
        <ul class="list-group" style="width: 80%; margin: 2% 10% 2% 10%;">
            <li class="list-group-item">
                <div class="jumbotron">
                    <h1 align="center">You are deleting type "{{ instance.name }}"</h1>
                </div>
                {% if not wrong_docs  and not given_out %}
                    <div align="center">
                        <a class="btn btn-danger" role="button" href="{% url 'type-delete' id=id %}">Delete</a>
                    </div>
                {% else %}
                    <div class="alert alert-danger" align="center">
                        This type is associated with some documents, delete them before deleting type.
                    </div>

                    <table class="table">
                        {% for doc in given_out %}
                            <tr>
                                <td><a href="{{ doc.get_absolute_url }}">
                                    {{ doc.title }}
                                </a></td>
                                <td>
                                    {{ doc.type }}
                                </td>
                                {% if perms.library.delete_document %}
                                    <td>
                                        <h6 title="Imposible to delete" class="text-danger">Given out</h6>
                                    </td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                        {% for docs in wrong_docs %}
                            <tr>
                                <td><a href="{{ docs.get_absolute_url }}">
                                    {{ docs.title }}
                                </a></td>
                                <td>
                                    {{ docs.type }}
                                </td>
                                {% if perms.library.delete_document %}
                                    <td>
                                        <a href="{% url 'document-delete' pk=docs.id %}" class="btn btn-danger"
                                           role="button">Delete</a>
                                    </td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </li>
        </ul>

    {% else %} You are not allowed to be here
    {% endif %}


    </body>
{% endblock %}

library/templates/upload_prompt.html
<form action="{% url "document-upload-complete" %}" method="post">
  {% csrf_token %}
  {{ direct_form }}
  <input type="submit" value="Submit" />
</form>